In [1]:
import pandas as pd
import numpy as np

In [2]:

import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.layers import Bidirectional, LSTM, Dropout, Dense
import pandas as pd
import seaborn as sns
from pylab import rcParams
import matplotlib.pyplot as plt
from matplotlib import rc
from pandas.plotting import register_matplotlib_converters

In [3]:
from tensorflow.keras.optimizers import Adam


In [4]:
df = pd.read_csv("C:/Users/7kingdom/Documents/카카오워크 받은 파일/pamap2.csv")

df

Unnamed: 0  timestamp  activityID  heartrate  handTemperature  \
0             2932      37.70           1      100.0          30.3750   
1             2943      37.81           1      100.0          30.3750   
2             2954      37.92           1      100.0          30.3750   
3             2965      38.03           1      100.0          30.3750   
4             2976      38.14           1      101.0          30.3750   
...            ...        ...         ...        ...              ...   
118511     2818402    3629.66           5      195.0          30.8125   
118512     2818413    3629.77           5      195.0          30.8125   
118513     2818423    3629.87           5      195.0          30.8125   
118514     2818435    3629.99           5      195.0          30.8125   
118515     2818445    3630.09           5      195.0          30.8125   

        handAcc16_1  handAcc16_2  handAcc16_3  handAcc6_1  handAcc6_2  ...  \
0          2.301060      7.25857      6.09259    2.207200     7.24042  ...   
1          2.246150      7.48180      5.55219    2.251300     7.40595  ...   
2          2.300000      7.10681      6.09309    2.346130     7.46611  ...   
3          2.494550      7.52335      6.17157    2.591060     7.76653  ...   
4          2.716540      8.30596      4.78671    2.595960     7.94641  ...   
...             ...          ...          ...         ...         ...  ...   
118511     0.565086      2.59595      9.27677    0.660681     2.70904  ...   
118512     0.570697      2.82459      9.39155    0.495537     2.75557  ...   
118513     0.756704      2.78452      9.31749    0.781122     2.72325  ...   
118514     0.530504      2.67279      9.35297    0.540382     2.87591  ...   
118515     0.644139      2.70986      9.35454    0.630675     2.81489  ...   

        ankleGyro2  ankleGyro3  ankleMagne1  ankleMagne2  ankleMagne3  \
0        -0.048878   -0.006328     -60.2040     -37.1225     -57.8847   
1        -0.017912    0.015243     -60.7820     -36.2116     -58.4891   
2        -0.011798    0.011387     -61.4531     -36.2983     -58.4845   
3        -0.009233    0.005823     -62.0065     -36.7217     -58.3608   
4        -0.042562   -0.009289     -60.4311     -37.5412     -59.0013   
...            ...         ...          ...          ...          ...   
118511   -0.002287   -0.017737     -17.6912      12.0079      26.5782   
118512   -0.007246    0.007512     -17.6928      12.0076      26.4364   
118513    0.003818    0.017649     -17.9459      11.7619      26.1521   
118514   -0.003649   -0.002610     -18.2103      12.4200      26.5759   
118515   -0.009639    0.006757     -18.0830      12.2841      26.2929   

        ankleOrientation1  ankleOrientation2  ankleOrientation3  \
0                1.000000           0.000000           0.000000   
1                1.000000           0.000000           0.000000   
2                1.000000           0.000000           0.000000   
3                1.000000           0.000000           0.000000   
4                1.000000           0.000000           0.000000   
...                   ...                ...                ...   
118511           0.164776           0.798149           0.227263   
118512           0.166393           0.797223           0.228965   
118513           0.166735           0.797039           0.229771   
118514           0.168936           0.795763           0.231222   
118515           0.170868           0.795143           0.232727   

        ankleOrientation4  subject_id  
0                0.000000           1  
1                0.000000           1  
2                0.000000           1  
3                0.000000           1  
4                0.000000           1  
...                   ...         ...  
118511           0.533065           8  
118512           0.533221           8  
118513           0.533041           8  
118514           0.533628           8  
118515           0.533282           8  

[118516 rows x 56 columns]

In [5]:
df.columns

Index(['Unnamed: 0', 'timestamp', 'activityID', 'heartrate', 'handTemperature',
       'handAcc16_1', 'handAcc16_2', 'handAcc16_3', 'handAcc6_1', 'handAcc6_2',
       'handAcc6_3', 'handGyro1', 'handGyro2', 'handGyro3', 'handMagne1',
       'handMagne2', 'handMagne3', 'handOrientation1', 'handOrientation2',
       'handOrientation3', 'handOrientation4', 'chestTemperature',
       'chestAcc16_1', 'chestAcc16_2', 'chestAcc16_3', 'chestAcc6_1',
       'chestAcc6_2', 'chestAcc6_3', 'chestGyro1', 'chestGyro2', 'chestGyro3',
       'chestMagne1', 'chestMagne2', 'chestMagne3', 'chestOrientation1',
       'chestOrientation2', 'chestOrientation3', 'chestOrientation4',
       'ankleTemperature', 'ankleAcc16_1', 'ankleAcc16_2', 'ankleAcc16_3',
       'ankleAcc6_1', 'ankleAcc6_2', 'ankleAcc6_3', 'ankleGyro1', 'ankleGyro2',
       'ankleGyro3', 'ankleMagne1', 'ankleMagne2', 'ankleMagne3',
       'ankleOrientation1', 'ankleOrientation2', 'ankleOrientation3',
       'ankleOrientation4', 'subject_id']

In [6]:
h_features = df[[ 'handAcc16_1', 'handAcc16_2', 'handAcc16_3', 'handAcc6_1', 'handAcc6_2',
       'handAcc6_3', 'handGyro1', 'handGyro2', 'handGyro3', 'handMagne1',
       'handMagne2', 'handMagne3','activityID']]

h_features


handAcc16_1  handAcc16_2  handAcc16_3  handAcc6_1  handAcc6_2  \
0          2.301060      7.25857      6.09259    2.207200     7.24042   
1          2.246150      7.48180      5.55219    2.251300     7.40595   
2          2.300000      7.10681      6.09309    2.346130     7.46611   
3          2.494550      7.52335      6.17157    2.591060     7.76653   
4          2.716540      8.30596      4.78671    2.595960     7.94641   
...             ...          ...          ...         ...         ...   
118511     0.565086      2.59595      9.27677    0.660681     2.70904   
118512     0.570697      2.82459      9.39155    0.495537     2.75557   
118513     0.756704      2.78452      9.31749    0.781122     2.72325   
118514     0.530504      2.67279      9.35297    0.540382     2.87591   
118515     0.644139      2.70986      9.35454    0.630675     2.81489   

        handAcc6_3  handGyro1  handGyro2  handGyro3  handMagne1  handMagne2  \
0          5.95555  -0.069961  -0.018328   0.004582     9.15626   -67.18250   
1          5.65313  -0.431227   0.002685  -0.062964     9.14612   -67.39360   
2          6.12103   0.075692  -0.030792   0.005246     9.69163   -67.08980   
3          6.27112  -0.259058  -0.267895  -0.038533     9.58694   -67.08820   
4          4.86635   0.377115  -0.023688  -0.020670     8.59622   -67.14860   
...            ...        ...        ...        ...         ...         ...   
118511     9.44024   0.039195   0.012003  -0.026437    17.71230    -4.80473   
118512     9.47051   0.011127   0.038150   0.059271    18.33580    -5.21004   
118513     9.40988   0.000674   0.034051   0.008866    17.71400    -4.92892   
118514     9.30409  -0.048145   0.034565  -0.001782    18.08540    -4.82465   
118515     9.34943  -0.004483  -0.001148   0.039415    17.95720    -4.94146   

        handMagne3  activityID  
0         -20.0857           1  
1         -20.5508           1  
2         -21.2481           1  
3         -20.8997           1  
4         -20.1947           1  
...            ...         ...  
118511    -41.8342           5  
118512    -41.4393           5  
118513    -41.8335           5  
118514    -41.8349           5  
118515    -41.1777           5  

[118516 rows x 13 columns]

In [7]:
c_features = df[[ 'chestAcc16_1', 'chestAcc16_2', 'chestAcc16_3', 'chestAcc6_1',
       'chestAcc6_2', 'chestAcc6_3', 'chestGyro1', 'chestGyro2', 'chestGyro3',
       'chestMagne1', 'chestMagne2', 'chestMagne3', 'activityID']]

c_features

chestAcc16_1  chestAcc16_2  chestAcc16_3  chestAcc6_1  chestAcc6_2  \
0           0.352225       9.72437     -1.686650     0.173568      9.69512   
1           0.125825       9.72560     -1.613310     0.143761      9.71023   
2           0.199567       9.64954     -1.689170     0.083704      9.75569   
3           0.279626       9.80069     -1.572050     0.114698      9.78564   
4           0.428255       9.64882     -1.685030     0.218926      9.60427   
...              ...           ...           ...          ...          ...   
118511     -2.176960       9.63375      0.397475    -2.399840      9.77329   
118512     -2.145710       9.63208      0.165721    -2.266810      9.53169   
118513     -1.882640       9.51751      0.054697    -2.161590      9.57682   
118514     -1.867470       9.63384      0.557966    -2.128490      9.69697   
118515     -1.948720       9.89635      0.362036    -2.039800      9.84828   

        chestAcc6_3  chestGyro1  chestGyro2  chestGyro3  chestMagne1  \
0         -1.534140    0.000275   -0.013352   -0.039315     0.462317   
1         -1.503690   -0.029411   -0.037321   -0.033805     1.113440   
2         -1.533420   -0.009560   -0.055878   -0.044714     1.032800   
3         -1.412620   -0.067753    0.020297   -0.012148     0.671351   
4         -1.398660    0.007856    0.001881   -0.058687     2.177730   
...             ...         ...         ...         ...          ...   
118511     0.703170    0.019680    0.018043   -0.013087    21.723400   
118512     0.565652    0.056830   -0.038897    0.005755    21.973900   
118513     0.504698   -0.060698   -0.026238    0.049355    21.971700   
118514     0.882662   -0.025373    0.022089    0.019818    21.863500   
118515     0.459413    0.131878   -0.028070    0.005272    21.216700   

        chestMagne2  chestMagne3  activityID  
0          -50.7110     42.92280           1  
1          -50.1898     44.64950           1  
2          -50.8441     43.17650           1  
3          -50.2744     43.29430           1  
4          -51.2222     43.68360           1  
...             ...          ...         ...  
118511     -30.6849      8.91800           5  
118512     -29.9201      8.63339           5  
118513     -30.6947      9.48380           5  
118514     -30.8185      8.35572           5  
118515     -30.9238      8.63383           5  

[118516 rows x 13 columns]

In [8]:
from sklearn.preprocessing import StandardScaler

h_x = h_features[['handAcc16_1' , 'handAcc16_2' , 'handAcc16_3' ,
    'handAcc6_1' , 'handAcc6_2' , 'handAcc6_3' ,
    'handGyro1' , 'handGyro2',   'handGyro3' ,      
    'handMagne1',  'handMagne2' , 'handMagne3']]
h_y = h_features['activityID']  


h_scaler = StandardScaler()
h_x = h_scaler.fit_transform(h_x)

scaled_h_x = pd.DataFrame(data = h_x, columns = ['handAcc16_1' , 'handAcc16_2' , 'handAcc16_3' ,
    'handAcc6_1' , 'handAcc6_2' , 'handAcc6_3' ,
    'handGyro1' , 'handGyro2',   'handGyro3' ,      
    'handMagne1',  'handMagne2' , 'handMagne3'])

scaled_h_x['label'] = h_y.values

In [9]:
c_x = c_features[[ 'chestAcc16_1', 'chestAcc16_2', 'chestAcc16_3', 'chestAcc6_1',
       'chestAcc6_2', 'chestAcc6_3', 'chestGyro1', 'chestGyro2', 'chestGyro3',
       'chestMagne1', 'chestMagne2', 'chestMagne3']]
c_y = c_features['activityID']  

c_scaler = StandardScaler()
c_x = c_scaler.fit_transform(c_x)

scaled_c_x = pd.DataFrame(data = c_x, columns = ['chestAcc16_1', 'chestAcc16_2', 'chestAcc16_3', 'chestAcc6_1',
       'chestAcc6_2', 'chestAcc6_3', 'chestGyro1', 'chestGyro2', 'chestGyro3',
       'chestMagne1', 'chestMagne2', 'chestMagne3'])
scaled_c_x['label'] = c_y.values

In [10]:
from sklearn.model_selection import train_test_split

HX_train, HX_test, Hy_train, Hy_test = train_test_split(scaled_h_x, 
                                                    scaled_h_x["label"],
                                                    test_size = 0.95, 
                                                    shuffle = True, 
                                                    random_state = 21)

In [11]:
from sklearn.model_selection import train_test_split

CX_train, CX_test, Cy_train, Cy_test = train_test_split(scaled_c_x, 
                                                    scaled_c_x["label"],
                                                    test_size = 0.95, 
                                                    shuffle = True, 
                                                    random_state = 21)

In [12]:
TIME_STEPS = 64
STEP = 64

In [13]:
from scipy import stats

def create_dataset(X, y, time_steps=1, step=1):
    Xs, ys = [], []
    for i in range(0, len(X) - time_steps, step):
        v = X.iloc[i:(i + time_steps)].values
        labels = y.iloc[i: i + time_steps]
        Xs.append(v)        
        ys.append(stats.mode(labels)[0][0])
    return np.array(Xs), np.array(ys).reshape(-1, 1)


HXs_train, Hys_train = create_dataset(HX_train[['handAcc16_1' , 'handAcc16_2' , 'handAcc16_3' ,
    'handAcc6_1' , 'handAcc6_2' , 'handAcc6_3' ,
    'handGyro1' , 'handGyro2',   'handGyro3' ,      
    'handMagne1',  'handMagne2' , 'handMagne3']], HX_train.label, TIME_STEPS, STEP)
HXs_test, Hys_test = create_dataset(HX_test[['handAcc16_1' , 'handAcc16_2' , 'handAcc16_3' ,
    'handAcc6_1' , 'handAcc6_2' , 'handAcc6_3' ,
    'handGyro1' , 'handGyro2',   'handGyro3' ,      
    'handMagne1',  'handMagne2' , 'handMagne3']], HX_test.label, TIME_STEPS, STEP)

print(HXs_train.shape, Hys_train.shape)

C:\Users\7kingdom\AppData\Local\Temp\ipykernel_22424\4023760221.py:9: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  ys.append(stats.mode(labels)[0][0])
C:\Users\7kingdom\AppData\Local\Temp\ipykernel_22424\4023760221.py:9: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning

(92, 64, 12) (92, 1)


In [14]:
CXs_train, Cys_train = create_dataset(CX_train[['chestAcc16_1', 'chestAcc16_2', 'chestAcc16_3', 'chestAcc6_1',
       'chestAcc6_2', 'chestAcc6_3', 'chestGyro1', 'chestGyro2', 'chestGyro3',
       'chestMagne1', 'chestMagne2', 'chestMagne3']], CX_train.label, TIME_STEPS, STEP)
CXs_test, Cys_test = create_dataset(CX_test[['chestAcc16_1', 'chestAcc16_2', 'chestAcc16_3', 'chestAcc6_1',
       'chestAcc6_2', 'chestAcc6_3', 'chestGyro1', 'chestGyro2', 'chestGyro3',
       'chestMagne1', 'chestMagne2', 'chestMagne3']], CX_test.label, TIME_STEPS, STEP)

print(CXs_train.shape, Cys_train.shape)

C:\Users\7kingdom\AppData\Local\Temp\ipykernel_22424\4023760221.py:9: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  ys.append(stats.mode(labels)[0][0])
C:\Users\7kingdom\AppData\Local\Temp\ipykernel_22424\4023760221.py:9: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning

(92, 64, 12) (92, 1)


In [15]:
from sklearn.preprocessing import OneHotEncoder

enc = OneHotEncoder(handle_unknown = "ignore", sparse = False)
enc = enc.fit(Hys_train)

Hyss_train = enc.transform(Hys_train)
Hyss_test = enc.transform(Hys_test)

In [16]:
from sklearn.preprocessing import OneHotEncoder

enc = OneHotEncoder(handle_unknown = "ignore", sparse = False)
enc = enc.fit(Cys_train)

Cyss_train = enc.transform(Cys_train)
Cyss_test = enc.transform(Cys_test)

In [17]:
print("HXs_train.shape: ", HXs_train.shape)
print("HXs_test.shape ", HXs_test.shape)
print("Hyss_train.shape ", Hyss_train.shape)
print("Hyss_test.shape ", Hyss_test.shape)

HXs_train.shape:  (92, 64, 12)
HXs_test.shape  (1759, 64, 12)
Hyss_train.shape  (92, 6)
Hyss_test.shape  (1759, 6)


In [18]:

verbose,epochs,batch_size=1,10,32 

n_timesteps,n_features,n_outputs=HXs_train.shape[1],HXs_train.shape[2],Hyss_train.shape[1]

In [19]:
n_timesteps, n_features, n_outputs
# 40에 10

(64, 12, 6)

<h3>핸드로 모델 만들기<h3>

In [20]:

inputs=keras.Input(shape=(n_timesteps,n_features))

conv_1=tf.keras.layers.Conv1D(filters=64,kernel_size=5,strides=2,activation='relu')(inputs)
maxpool_1=tf.keras.layers.MaxPooling1D(pool_size=2,strides=2)(conv_1)

conv_2=tf.keras.layers.Conv1D(filters=96,kernel_size=3,strides=1,activation='relu')(maxpool_1)
avg_pooling=tf.keras.layers.GlobalAveragePooling1D()(conv_2)
batch_norm=tf.keras.layers.BatchNormalization()(avg_pooling)

output=tf.keras.layers.Dense(n_outputs,activation='softmax')(batch_norm)
h_model=tf.keras.Model(inputs=inputs,outputs=output)
h_model.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 64, 12)]          0         
                                                                 
 conv1d (Conv1D)             (None, 30, 64)            3904      
                                                                 
 max_pooling1d (MaxPooling1  (None, 15, 64)            0         
 D)                                                              
                                                                 
 conv1d_1 (Conv1D)           (None, 13, 96)            18528     
                                                                 
 global_average_pooling1d (  (None, 96)                0         
 GlobalAveragePooling1D)                                         
                                                                 
 batch_normalization (Batch  (None, 96)                384   

In [21]:
h_model.compile(optimizer=Adam(learning_rate = 0.001), loss = 'categorical_crossentropy', metrics = ['accuracy'])

In [22]:
history = h_model.fit(HXs_train, Hyss_train, epochs = 30, batch_size = 32, validation_split = 0.1, shuffle = True)
print(h_model.summary())

Epoch 1/30
3/3 [==============================] - 2s 156ms/step - loss: 2.1481 - accuracy: 0.1707 - val_loss: 1.9641 - val_accuracy: 0.2000
Epoch 2/30
3/3 [==============================] - 0s 22ms/step - loss: 1.4631 - accuracy: 0.4756 - val_loss: 1.9563 - val_accuracy: 0.1000
Epoch 3/30
3/3 [==============================] - 0s 22ms/step - loss: 1.0689 - accuracy: 0.7439 - val_loss: 1.9382 - val_accuracy: 0.2000
Epoch 4/30
3/3 [==============================] - 0s 23ms/step - loss: 0.8427 - accuracy: 0.8537 - val_loss: 1.9262 - val_accuracy: 0.2000
Epoch 5/30
3/3 [==============================] - 0s 21ms/step - loss: 0.6626 - accuracy: 0.9024 - val_loss: 1.9139 - val_accuracy: 0.2000
Epoch 6/30
3/3 [==============================] - 0s 22ms/step - loss: 0.5189 - accuracy: 0.9390 - val_loss: 1.8998 - val_accuracy: 0.2000
Epoch 7/30
3/3 [==============================] - 0s 22ms/step - loss: 0.4026 - accuracy: 0.9512 - val_loss: 1.8865 - val_accuracy: 0.2000
Epoch 8/30
3/3 [==========

In [23]:
from mlxtend.plotting import plot_confusion_matrix
from sklearn.metrics import confusion_matrix
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score


<h3>헨드로 핸드<h3>

In [24]:
base_loss,base_accuracy=h_model.evaluate(HXs_test,Hyss_test,batch_size=batch_size,verbose=1)
  
score=base_accuracy*100
print('Accuracy >{:f}'.format(score))
print('Base Loss >{:.2f}'.format(base_loss))

55/55 [==============================] - 0s 3ms/step - loss: 1.7516 - accuracy: 0.2013
Accuracy >20.125072
Base Loss >1.75


In [25]:
y_test_arg=np.argmax(Hyss_test,axis=1)
Y_pred = np.argmax(h_model.predict(HXs_test), axis=1)

print('Confusion Matrix')
print(confusion_matrix(y_test_arg, Y_pred))

55/55 [==============================] - 0s 3ms/step
Confusion Matrix
[[ 59   9 100  36   0 201]
 [ 17   7  70  40   0 115]
 [  7   5  80  60   0 134]
 [ 14   8 160  93   0 329]
 [  0   0   0   0   0   1]
 [ 10   2  46  41   0 115]]


<h3>핸드로 체스트<h3>

In [26]:
base_loss,base_accuracy=h_model.evaluate(CXs_test,Cyss_test,batch_size=batch_size,verbose=1)
  
score=base_accuracy*100
print('Accuracy >{:f}'.format(score))
print('Base Loss >{:.2f}'.format(base_loss))

55/55 [==============================] - 0s 4ms/step - loss: 1.7777 - accuracy: 0.1814
Accuracy >18.135305
Base Loss >1.78


In [27]:
y_test_arg=np.argmax(Cyss_test,axis=1)
Y_pred = np.argmax(h_model.predict(CXs_test), axis=1)

print('Confusion Matrix')
print(confusion_matrix(y_test_arg, Y_pred))

55/55 [==============================] - 0s 2ms/step
Confusion Matrix
[[ 34   8  45  12   0 306]
 [  8  14  42  20   0 165]
 [  3  24  51  41   0 167]
 [ 13  31 110  81   0 369]
 [  0   0   0   0   0   1]
 [  5   7  35  28   0 139]]


<h3>체스트로 모델 만들기<h3>

In [28]:

inputs=keras.Input(shape=(n_timesteps,n_features))

conv_1=tf.keras.layers.Conv1D(filters=64,kernel_size=5,strides=2,activation='relu')(inputs)
maxpool_1=tf.keras.layers.MaxPooling1D(pool_size=2,strides=2)(conv_1)

conv_2=tf.keras.layers.Conv1D(filters=96,kernel_size=3,strides=1,activation='relu')(maxpool_1)
avg_pooling=tf.keras.layers.GlobalAveragePooling1D()(conv_2)
batch_norm=tf.keras.layers.BatchNormalization()(avg_pooling)

output=tf.keras.layers.Dense(n_outputs,activation='softmax')(batch_norm)
c_model=tf.keras.Model(inputs=inputs,outputs=output)
c_model.summary()

Model: "model_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_2 (InputLayer)        [(None, 64, 12)]          0         
                                                                 
 conv1d_2 (Conv1D)           (None, 30, 64)            3904      
                                                                 
 max_pooling1d_1 (MaxPoolin  (None, 15, 64)            0         
 g1D)                                                            
                                                                 
 conv1d_3 (Conv1D)           (None, 13, 96)            18528     
                                                                 
 global_average_pooling1d_1  (None, 96)                0         
  (GlobalAveragePooling1D)                                       
                                                                 
 batch_normalization_1 (Bat  (None, 96)                384 

In [29]:
c_model.compile(optimizer=Adam(learning_rate = 0.001), loss = 'categorical_crossentropy', metrics = ['accuracy'])

In [30]:
history = c_model.fit(CXs_train, Cyss_train, epochs = 30, batch_size = 32, validation_split = 0.1, shuffle = True)
print(c_model.summary())

Epoch 1/30
3/3 [==============================] - 2s 131ms/step - loss: 2.3218 - accuracy: 0.1585 - val_loss: 1.6912 - val_accuracy: 0.3000
Epoch 2/30
3/3 [==============================] - 0s 23ms/step - loss: 1.5541 - accuracy: 0.3537 - val_loss: 1.6960 - val_accuracy: 0.3000
Epoch 3/30
3/3 [==============================] - 0s 26ms/step - loss: 1.2054 - accuracy: 0.6463 - val_loss: 1.6986 - val_accuracy: 0.3000
Epoch 4/30
3/3 [==============================] - 0s 25ms/step - loss: 0.9730 - accuracy: 0.7683 - val_loss: 1.6884 - val_accuracy: 0.3000
Epoch 5/30
3/3 [==============================] - 0s 31ms/step - loss: 0.7785 - accuracy: 0.8537 - val_loss: 1.6734 - val_accuracy: 0.3000
Epoch 6/30
3/3 [==============================] - 0s 23ms/step - loss: 0.6331 - accuracy: 0.9024 - val_loss: 1.6619 - val_accuracy: 0.3000
Epoch 7/30
3/3 [==============================] - 0s 29ms/step - loss: 0.5071 - accuracy: 0.9634 - val_loss: 1.6524 - val_accuracy: 0.3000
Epoch 8/30
3/3 [==========

<h3> 체스트로 체스트 <h3>

In [31]:
base_loss,base_accuracy=c_model.evaluate(CXs_test,Cyss_test,batch_size=batch_size,verbose=1)
  
score=base_accuracy*100
print('Accuracy >{:f}'.format(score))
print('Base Loss >{:.2f}'.format(base_loss))

55/55 [==============================] - 0s 3ms/step - loss: 1.6304 - accuracy: 0.4093
Accuracy >40.932348
Base Loss >1.63


In [32]:
y_test_arg=np.argmax(Cyss_test,axis=1)
Y_pred = np.argmax(c_model.predict(CXs_test), axis=1)

print('Confusion Matrix')
print(confusion_matrix(y_test_arg, Y_pred))

55/55 [==============================] - 0s 3ms/step
Confusion Matrix
[[329   0   0  76   0   0]
 [ 97   0   1 151   0   0]
 [ 98   0   1 186   0   1]
 [215   0   0 388   0   1]
 [  0   0   0   1   0   0]
 [ 73   0   0 139   0   2]]


<h3>체스트로 핸드<h3>

In [33]:
base_loss,base_accuracy=c_model.evaluate(HXs_test,Hyss_test,batch_size=batch_size,verbose=1)
  
score=base_accuracy*100
print('Accuracy >{:f}'.format(score))
print('Base Loss >{:.2f}'.format(base_loss))

55/55 [==============================] - 0s 5ms/step - loss: 1.6643 - accuracy: 0.3661
Accuracy >36.611712
Base Loss >1.66


In [34]:
y_test_arg=np.argmax(Cyss_test,axis=1)
Y_pred = np.argmax(c_model.predict(CXs_test), axis=1)

print('Confusion Matrix')
print(confusion_matrix(y_test_arg, Y_pred))

55/55 [==============================] - 0s 3ms/step
Confusion Matrix
[[329   0   0  76   0   0]
 [ 97   0   1 151   0   0]
 [ 98   0   1 186   0   1]
 [215   0   0 388   0   1]
 [  0   0   0   1   0   0]
 [ 73   0   0 139   0   2]]
